---
title: "DBSCAN"
author: "rimashanda (19523214) dan choirun nisa(19523227)"
date: "12/5/2020"
output: html_document
---


```{r}
#Dataset yang digunakan dalam hierarchical clustering ini adalah data randu karena memiliki 400 data dan 3 fitur yaitu x,y, dan z.
library(factoextra)
data("randu")
df <- randu[, 1:2]
```

```{r}
plot(df, pch=16)
```
```{r}
#elbow method (bonus nilai)
# berdasarkan grafik yang muncul dibawah bisa kita tentukan dengan elbow method bahwa jumlah cluster terbaik yang dapat di assign berjumlah 8 cluster.Karena setelah dilihat akan ada beberapa nilai K yang mengalami penurunan paling besar dan selanjutnya nilai K akan turun secara perlahan-lahan sampai hasil dari nilai K tersebut stabil. Disini kita dapatkan nilai cluster K=7 ke K=8 kemudian dari K=8 ke K=9 terlihat penurunan secara drastis membentuk siku pada titik K=8, maka nilai cluster yang ideal adalah K=8.
set.seed(123)
k.max <- 15
data <- randu
wss <- sapply(1:k.max, 
              function(k){kmeans(data, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```

```{r}
#Jumlah cluster yang digunakan berjumlah 8 cluster sesuai dengan hasil elbow method. 
#Fitur yang digunakan dalam DBSCAN berjumlah 3 fitur yaitu x,y, dan z.
set.seed(123)
km.res <- kmeans(df, 8, nstart = 25)
fviz_cluster(km.res, df, frame = FALSE, geom = "point")
```
```{r}
library("fpc")
set.seed(123)
db <- dbscan(df, eps = 0.15, MinPts = 3)
plot(db, df, main = "DBSCAN", frame = FALSE)
```

# Alternatif lain menggunakan fungsi plot cluster dari factoextra
```{r}
library("factoextra")
fviz_cluster(db, df, stand = FALSE, frame = FALSE, geom = "point")
```
```{r}
print(db)
```
```{r}
db$cluster
```
```{r}
library(dbscan)
```
```{r}
kNNdistplot(df, k =  5)
abline(h = 0.15, lty = 2)
```