---
title: "Hierarchical"
author: "rimashanda (19523214) dan choirun nisa(19523227)"
date: "12/5/2020"
output: html_document
---

```{r}
#Dataset yang digunakan dalam hierarchical clustering ini adalah data randu karena memiliki 400 data dan 3 fitur yaitu x,y, dan z.
randu
```

```{r}
summary(randu)
```

```{r}
#elbow method (bonus nilai)
# berdasarkan grafik yang muncul dibawah bisa kita tentukan dengan elbow method bahwa jumlah cluster terbaik yang dapat di assign berjumlah 8 cluster.Karena setelah dilihat akan ada beberapa nilai K yang mengalami penurunan paling besar dan selanjutnya nilai K akan turun secara perlahan-lahan sampai hasil dari nilai K tersebut stabil. Disini kita dapatkan nilai cluster K=7 ke K=8 kemudian dari K=8 ke K=9 terlihat penurunan secara drastis membentuk siku pada titik K=8, maka nilai cluster yang ideal adalah K=8.
set.seed(123)
k.max <- 15
data <- randu
wss <- sapply(1:k.max, 
              function(k){kmeans(data, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```

```{r}
#Jumlah cluster yang digunakan berjumlah 8 cluster sesuai dengan hasil elbow method. 
#Fitur yang digunakan dalam DBSCAN berjumlah 3 fitur yaitu x,y, dan z.
randu.new <- randu[, 1:3]
randu.class <- randu[,]
set.seed(1000)
result <- kmeans(randu.new, 8)
```


```{r}
df <- data.frame(States=rownames(randu), randu)
par(las=2) # make label text perpendicular to axis
par(mar=c(5,8,4,2)) # increase y-axis margin.
barplot(df$x, names.arg = df$States, horiz = TRUE, cex.names = 0.5, xlab = "Variabel X RANDU")
```

```{r}
barplot(df$y, names.arg = df$States, horiz = TRUE, cex.names = 0.5 , xlab = "Variabel Y Randu")
```
```{r}
barplot(df$z, names.arg = df$States, horiz = TRUE, cex.names = 0.5 , xlab = "Variabel Z Randu")
```

```{r}
df <- scale(df[, 2:3])
d <- dist(df, method = "euclidean")
clusters <- hclust(d, method = "complete" )
plot(clusters, cex = 0.6, hang = -1)
```
```{r}
plot(clusters, cex = 0.7, hang = -4)
rect.hclust(clusters, k = 6, border = 2:3)
```


