---
title: "K-mean"
author: "rimashanda(19523214) dan choirun nisa(19523227)"
date: "12/5/2020"
output: html_document
---

```{r}
#Dataset yang digunakan dalam hierarchical clustering ini adalah data randu karena memiliki 400 data dan 3 fitur yaitu x,y, dan z.
library("datasets")
data("randu")
```
```{r}
summary(randu)
```

```{r}

#elbow method (bonus nilai )
# berdasarkan grafik yang muncul dibawah bisa kita tentukan dengan elbow method bahwa jumlah cluster terbaik yang dapat di assign berjumlah 8 cluster.Karena setelah dilihat akan ada beberapa nilai K yang mengalami penurunan paling besar dan selanjutnya nilai K akan turun secara perlahan-lahan sampai hasil dari nilai K tersebut stabil. Disini kita dapatkan nilai cluster K=7 ke K=8 kemudian dari K=8 ke K=9 terlihat penurunan secara drastis membentuk siku pada titik K=8, maka nilai cluster yang ideal adalah K=8.
set.seed(123)
k.max <- 15
data <- randu
wss <- sapply(1:k.max, 
              function(k){kmeans(data, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```

```{r}
randu.new <- randu[, 1:3]
randu.class <- randu[,]
set.seed(1000)
result <- kmeans(randu.new, 8)
```
```{r}
par(mfrow=c(2,2), mar=c(5,4,2,2))
plot(randu.new[, c(1,2)], col=result$cluster)
plot(randu.new[, c(1,2)], col=randu.class)
plot(randu.new[, c(2,3)], col=result$cluster)
plot(randu.new[, c(2,3)], col=randu.class)
```
```{r}
result$tot.withinss
```
```{r}
#Jumlah cluster yang digunakan berjumlah 8 cluster sesuai dengan hasil elbow method. 
#Fitur yang digunakan dalam k-means berjumlah 3 fitur yaitu x,y, dan z.
attributes(randu)$names
```
```{r}
randu.new$cluster <- factor(result$cluster)
centers <- as.data.frame(result$centers)
library(ggplot2)
ggplot() + 
  geom_point(data=randu.new, aes(x=x, y=y,color=cluster))  +
  geom_point(data=centers, aes(x=x, y=y, color="Center"), 
             size=60, alpha=.2, show.legend = FALSE)
```


